# Generated by Django 3.1.3 on 2020-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20201206_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_Id',
            new_name='user_id',
        ),
    ]
