# Generated by Django 3.1.3 on 2020-12-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20201207_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_Id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
