# Generated by Django 3.1.3 on 2020-12-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20201207_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
