# Generated by Django 3.1.3 on 2020-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20201209_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This user does not have a bio yet.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='This user does not have a status yet.', max_length=30),
        ),
    ]
